### ISSUE TITLE
Ubuntu 15.04 - Blank/Transparent Gif

### ISSUE THREAD

**Issue by albertossilva** [colinkeenan/silentcast#17] opened 2015-07-22 21:57 UTC
When I use silencast, all images and the gif get blank/transparent

 [Blank images and gif](http://screencloud.net/v/w8i6)

**Comment by Seth-Johnson** [comment] 2015-08-15 20:08
I have been experiencing this bug myself, but have so far been unable to determine if it is a bug with avconv/ffmpeg or the way silentcast uses it.

**Comment by colinkeenan** [comment] 2015-08-31 21:51
Can you check if v2.1 solves this problem?

**Comment by Seth-Johnson** [comment] 2015-09-13 00:12
v2.1 seems to work on my end, although I don't know why, temptoanim hasn't been touched by any of the recent changes.. @albertossilva what version of avconv do you have installed? Check by running `avconv -version` please. On my 15.04 box I have:

    seth@tanager:~/Downloads/silentcast-2.1$ avconv -version
    avconv version 11.2-6:11.2-1, Copyright (c) 2000-2014 the Libav developers
      built on Jan 18 2015 05:12:33 with gcc 4.9.2 (Ubuntu 4.9.2-10ubuntu2)
    avconv 11.2-6:11.2-1
    libavutil     54.  3. 0 / 54.  3. 0
    libavcodec    56.  1. 0 / 56.  1. 0
    libavformat   56.  1. 0 / 56.  1. 0
    libavdevice   55.  0. 0 / 55.  0. 0
    libavfilter    5.  0. 0 /  5.  0. 0
    libavresample  2.  1. 0 /  2.  1. 0  
    libswscale     3.  0. 0 /  3.  0. 0

**Comment by Seth-Johnson** [comment] 2015-09-13 01:38
A friend of mine was unable to reproduce on 14.04 as well, running Silentcast 2.0 with avconv version:  

    $ avconv -version 
    avconv version 9.18-6:9.18-0ubuntu0.14.04.1, Copyright (c) 2000-2014 the Libav developers 
    built on Mar 16 2015 13:19:10 with gcc 4.8 (Ubuntu 4.8.2-19ubuntu1) 
    avconv 9.18-6:9.18-0ubuntu0.14.04.1 
    libavutil 52. 3. 0 / 52. 3. 0 
    libavcodec 54. 35. 0 / 54. 35. 0 
    libavformat 54. 20. 4 / 54. 20. 4 
    libavdevice 53. 2. 0 / 53. 2. 0 
    libavfilter 3. 3. 0 / 3. 3. 0
    libavresample 1. 0. 1 / 1. 0. 1 
    libswscale 2. 1. 1 / 2. 1. 1  

At this point I am unsure how to proceed, as I am unable to reproduce the issue any longer.

**Comment by colinkeenan** [comment] 2016-11-28 01:08
I think this is resolved with v2.4

**Closed by colinkeenan** 2016-11-28 01:08 UTC
